services:
  - type: web
    name: worst-case-ai
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn api:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: OPENAI_API_KEY
        value: ${OPENAI_API_KEY}
